### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

a = np.array([1, 2, 3])
print(a)
print(type(a)) # This is a 1-D Array -> vector

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
# 2D and 3D
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(type(b)) # can also -> matrix
print(b.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [3]:
c = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(c)
print(type(c), c.shape, c.ndim)
print()
c = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
print(c)
print(type(c), c.shape, c.ndim) # -> 3D Tensor

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
<class 'numpy.ndarray'> (1, 4, 2) 3

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'> (2, 2, 2) 3


In [4]:
# dtype - > Till now item datatype was integer, now what if  you want float data type array?
print(np.array([1, 2, 3], dtype=float))
print(np.array([1, 2, 3], dtype=bool))
print(np.array([1, 2, 3], dtype=complex))

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [34]:
# np.arange
print(np.arange(1, 11))
print(np.arange(1, 11, 2))
np.arange(10)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# with reshape
np.arange(1, 11) # -> this is a vector/1-D Tensor/array with 10 items
# np.arange().reshape() is used to convert a given numpy array to another dimension
np.arange(1, 11).reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [37]:
np.arange(12).reshape(3, 4) 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
np.arange(15).reshape(5, 5)


ValueError: cannot reshape array of size 15 into shape (5,5)

In [39]:
# with reshape
np.arange(16).reshape(2,2,2,2) # -> 4-D Tensor

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [42]:
# np.ones and np.zeros
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((3,4))

array([[0.85721156, 0.31248316, 0.08807828, 0.35230774],
       [0.96813914, 0.44681708, 0.56396358, 0.53020065],
       [0.03277116, 0.28543753, 0.09521082, 0.87967034]])

In [46]:
# np.linspace -> values are linearly separated within a range
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [48]:
np.linspace(-10, 10, 10, dtype='int')

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [47]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [65]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1, a2, a3, sep='\n\n')
a3 # -> all are numpy arrays

[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [66]:
# ndim
a3.ndim

3

In [67]:
# shape
print(a1.shape)
a1

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [68]:
# shape
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [69]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [70]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [71]:
# itemsize
print(a1.itemsize)
print(a2.itemsize)

4
8


In [72]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [87]:
# astype
a3.astype(np.int32)
a4 = [1.3, 2.4, 5.8]
print(a4)
a4 = np.array(a4, dtype='int')
print(a4)
a3

[1.3, 2.4, 5.8]
[1 2 5]


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### Array Operations

In [17]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
a2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
# scalar operations

# arithmetic
print(a1+2)
print(a1*2)
a1 ** 2

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [19]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [31]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
# vector operations
# arithmetic
a1+a2 # itemewise gets added since equal shape

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [69]:
a3 = np.arange(9).reshape((3, 3))

In [73]:
a1*a3 # -> neither dot or cross product, it is multiplication of arrays, item by item

array([[  0.,  52.,  68.],
       [255., 264., 440.],
       [120.,  21., 256.]])

In [27]:
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [28]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [29]:
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

### Array Functions

In [36]:
a1 = np.random.random((3,3))
print(a1)
a1 = np.round(a1*100)
a1

[[0.03067308 0.52306134 0.34125748]
 [0.85336181 0.65526499 0.87767051]
 [0.19703172 0.02782877 0.32346656]]


array([[ 3., 52., 34.],
       [85., 66., 88.],
       [20.,  3., 32.]])

In [37]:
# max/min/sum/prod
np.max(a1)

np.float64(88.0)

In [38]:
# max/min/sum/prod
np.min(a1)

np.float64(3.0)

In [39]:
# max/min/sum/prod
np.sum(a1)

np.float64(383.0)

In [40]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1)

np.float64(5027479142400.0)

In [46]:
# 0 -> col and 1 -> row
print(np.max(a1, axis=1))
print(np.min(a1, axis=1))
print(np.sum(a1, axis=1))
print(np.prod(a1, axis=1))
print(np.max(a1, axis=0))
print(np.min(a1, axis=0))
print(np.sum(a1, axis=0))
np.prod(a1, axis=0)

[52. 88. 32.]
[ 3. 66.  3.]
[ 89. 239.  55.]
[  5304. 493680.   1920.]
[85. 66. 88.]
[ 3.  3. 32.]
[108. 121. 154.]


array([ 5100., 10296., 95744.])

In [47]:
# mean/median/std/var
print(np.mean(a1))
np.mean(a1,axis=1)

42.55555555555556


array([29.66666667, 79.66666667, 18.33333333])

In [48]:
np.median(a1, axis=1)

array([34., 85., 20.])

In [51]:
print(np.std(a1))
np.std(a1, axis=1)

30.419697971731377


array([20.23747898,  9.7410928 , 11.8977122 ])

In [54]:
print(np.var(a1))
np.var(a1, axis=1)

925.3580246913581


array([409.55555556,  94.88888889, 141.55555556])

In [55]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.14112001,  0.98662759,  0.52908269],
       [-0.17607562, -0.02655115,  0.0353983 ],
       [ 0.91294525,  0.14112001,  0.55142668]])

In [60]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [61]:
# log and exponents
np.exp(a1)

array([[2.00855369e+01, 3.83100800e+22, 5.83461743e+14],
       [8.22301271e+36, 4.60718663e+28, 1.65163625e+38],
       [4.85165195e+08, 2.00855369e+01, 7.89629602e+13]])

In [62]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[ 79.,  51.,  22.],
       [ 26., 100.,  66.]])

In [66]:
np.floor(np.random.random((2, 3))*100)

array([[18., 92., 12.],
       [90., 76., 78.]])

In [67]:
np.ceil(np.random.random((2,3))*100)

array([[28., 69., 62.],
       [35.,  2., 78.]])

### Indexing and Slicing

In [74]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
a2[1,0]

np.int64(4)

In [77]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [78]:
a3[1,0,1]

np.int64(5)

In [79]:
a3[1,1,0]

np.int64(6)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a1[2:5:2] # -> exactly similar to python normal sequence slicing

array([2, 4])

`Let's have a look at >1 D slicing`

In [82]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
a2[0,:] # first row

array([0, 1, 2, 3])

In [86]:
a2[:, 2] # third column

array([ 2,  6, 10])

In [87]:
# What if I want 5,6,9,10
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [88]:
# what if we need 0, 3, 8, 11
a2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [91]:
#1, 3, 9, 11
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [92]:
# for 4, 7
a2[1, ::3]

array([4, 7])

In [94]:
# 1, 2, 3 ; 5, 6, 7
a2[:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [98]:
a3 = np.arange(27).reshape(3, 3, 3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [99]:
# To get second 2D Array:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [100]:
# Need first and last 2D Array
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [105]:
# second row of first 2D array
print(a3[0][1])
print(a3[0, 1, :])
a3[0, 1]

[3 4 5]
[3 4 5]


array([3, 4, 5])

In [106]:
# Middle column of second numpy array
a3[1, :, 1]

array([10, 13, 16])

In [107]:
# Get 22, 23, 25, 26
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [108]:
# 0, 2, 18, 20
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [ ]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [109]:
for i in np.nditer(a1):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [111]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape

In [118]:
# Transpose
print(a2)
print(np.transpose(a2))
print(a2)
print(a2.T)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [120]:
# ravel
print(a3)
print(a3.ravel())
a3

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### Stacking

In [122]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [123]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [124]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [125]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [127]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [128]:
np.hsplit(a4,5)

ValueError: array split does not result in an equal division

In [ ]:
# vertical splitting

In [129]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [130]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [131]:
np.vsplit(a5, 2)

ValueError: array split does not result in an equal division