**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [126]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [130]:
#Code here
a = np.nan * np.empty(10)
a[4] = 1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [6]:
#Code here
a = int(input("a: "))
b = int(input("b: "))
a1 = np.random.random((3, 4))
print(a1)
print(a1.mean())

a: 3
b: 4
[[0.49354653 0.67260527 0.46255418 0.63421469]
 [0.01635758 0.82746878 0.40787152 0.22408484]
 [0.38891372 0.57055477 0.91175979 0.13019401]]
0.4783438058019411


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [25]:
def create_2d(a, b):
  shape = a, b

  rows, cols = a, b
  if rows <=0 or cols <=0:
    return np.array([])

  elif rows ==1 and cols == 1:
    return np.ones((1, 1))

  arr = np.ones(shape)

  if rows >2 and cols >2:
    arr[1:-1, 1:-1] = 0

  return arr.astype(np.int32)

create_2d(2, 1)

array([[1],
       [1]], dtype=int32)

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [131]:
#Code here
a2 = np.random.random(10) # But there is a chance to get 0 in this, hence, not recommended
a2 = np.linspace(0, 1, 12)[1: -1] # Guarantees 0 and 1 never appears
a2

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [132]:
#Code here
np.eye(3, 4) # But this is not a identity matrix by definition of identity matrix
# hence, cannot do 3x4, but can do 3x3 identity matrix
np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [136]:
#Code here
ar3 = np.random.randint(0, 5, 25).reshape((5, 5))
print(ar3)
# if you want row rom 0 to 4, then:
ar4 = np.zeros((5, 5))
ar4 += np.arange(5)
print(ar4)

[[0 2 2 0 1]
 [3 1 2 4 4]
 [0 2 4 4 3]
 [4 0 4 0 2]
 [1 4 0 0 1]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [138]:
coordinates = np.random.randint(1, 100, (10, 2))
point = np.array([2, 3])
diff = ((coordinates - point)**2)
dist = np.sqrt(np.sum(diff, axis=1)).astype(int)
dist

array([117,  56,  50,  72,  43,  13,  96,  70, 115,  97])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [140]:
#Code here
print(np.unravel_index(99, (6, 7, 8)))

(np.int64(1), np.int64(5), np.int64(3))


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [143]:
a = input().strip().split()
a = np.array(a[::-1],dtype=np.float32)
a

1 2 3 4 -8 -10


array([-10.,  -8.,   4.,   3.,   2.,   1.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [62]:
#Code here
inp = eval(input())
inp.size

np.array([])


0

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [148]:
#Code here
def softmax(arr):

  if type(arr) != np.ndarray:
    raise TypeError("Requires Numpy Array")
  elif arr.ndim >1:
    raise TypeError("Require a 1D Array")

  sum = np.sum(np.exp(arr))
  return np.exp(arr)/sum

softmax(np.array([86.03331084, 37.7285648  ,48.64908087, 87.16563062, 38.40852563, 37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [68]:
#Code here

def vstack_arrays(*args):
  for arg in args:
    if not isinstance(arg, np.ndarray):
      print(f"Not possible as {arg} is not numpy array")
      return
  return np.vstack(args)

a= np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])

b= np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

vstack_arrays(a, b)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [158]:
def date_array(start, end):
  if not isinstance(start, str) or not isinstance(end, str):
    raise TypeError

  months_days = {
    1: 31,
    2: 28,
    3: 31,
    4: 30,
    5: 31,
    6: 30,
    7: 31,
    8: 31,
    9: 30,
    10: 31,
    11: 30,
    12: 31
  }

  end_y, end_m, end_d = [int(i) for i in end.split('-')]
  if end_d == months_days[end_m]:
    end_d = 1
    end_m += 1
  else:
    end_d += 1
  if end_m >12:
    end_y += 1
    end_m = 1

  end_m = f"0{end_m}" if end_m <10 else f"{end_m}"
  end_d = f"0{end_d}" if end_d <10 else f"{end_d}"
  final_end = '-'.join([str(end_y), end_m, end_d])

  return np.arange(np.datetime64(start), np.datetime64(final_end), dtype='datetime64[D]')
date_array(start = '2022-11-01', end = '2022-12-31')



array(['2022-11-01', '2022-11-02', '2022-11-03', '2022-11-04',
       '2022-11-05', '2022-11-06', '2022-11-07', '2022-11-08',
       '2022-11-09', '2022-11-10', '2022-11-11', '2022-11-12',
       '2022-11-13', '2022-11-14', '2022-11-15', '2022-11-16',
       '2022-11-17', '2022-11-18', '2022-11-19', '2022-11-20',
       '2022-11-21', '2022-11-22', '2022-11-23', '2022-11-24',
       '2022-11-25', '2022-11-26', '2022-11-27', '2022-11-28',
       '2022-11-29', '2022-11-30', '2022-12-01', '2022-12-02',
       '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06',
       '2022-12-07', '2022-12-08', '2022-12-09', '2022-12-10',
       '2022-12-11', '2022-12-12', '2022-12-13', '2022-12-14',
       '2022-12-15', '2022-12-16', '2022-12-17', '2022-12-18',
       '2022-12-19', '2022-12-20', '2022-12-21', '2022-12-22',
       '2022-12-23', '2022-12-24', '2022-12-25', '2022-12-26',
       '2022-12-27', '2022-12-28', '2022-12-29', '2022-12-30',
       '2022-12-31'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [44]:
#code here
arr = np.arange(12).reshape((3, 4))
means = np.mean(arr, axis=1, keepdims = True)
arr-means

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [164]:
#Code here
arr = np.arange(12).reshape((3,4))
# print(arr)
# temp = np.array(arr[:, 1])
# arr[:, 1] = arr[:, 0]
# arr[:, 0] = temp
# print(arr)

# much much simpler way:
arr[:, [1, 0]+list(range(2, arr.shape[-1]))]

array([[ 1,  0,  2,  3],
       [ 5,  4,  6,  7],
       [ 9,  8, 10, 11]])

In [165]:
print(arr)
arr[:, [0,1]] = arr[:, [1, 0]]
arr

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 1,  0,  2,  3],
       [ 5,  4,  6,  7],
       [ 9,  8, 10, 11]])

###`Q-16:` Replace odd elements in arrays with -1.

In [167]:
arr = np.arange(12).reshape(3, 4)
arr[arr %2 !=0] = -1
arr

array([[ 0, -1,  2, -1],
       [ 4, -1,  6, -1],
       [ 8, -1, 10, -1]])

In [84]:
ar1 = np.arange(12).reshape(3, 4)
np.vstack((ar1, np.arange(13, 25).reshape(3, 4)))
ar1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [176]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])


a[b>a] = b[b>a]
a

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [178]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[1203, 6281, 4025, 9347,   87],
       [7563,  419, 9212, 9125, 1658],
       [3107,  464,  303, 6404, 6593],
       [2363, 8499, 7682, 2632, 2613],
       [1239, 8551, 8029,  642,  370],
       [4936, 3999, 9607, 4070, 6397],
       [6458, 3754, 2493, 8462, 2868],
       [6888, 6623, 2323, 3049, 5450]])

In [180]:
#Code here
arr1[:, ::2]


array([[1203, 4025,   87],
       [7563, 9212, 1658],
       [3107,  303, 6593],
       [2363, 7682, 2613],
       [1239, 8029,  370],
       [4936, 9607, 6397],
       [6458, 2493, 2868],
       [6888, 2323, 5450]])

In [181]:
(arr1 - arr1.min())/(arr1.max()-arr1.min())

array([[0.11722689, 0.65063025, 0.41365546, 0.97268908, 0.        ],
       [0.78529412, 0.03487395, 0.9585084 , 0.94936975, 0.16502101],
       [0.31722689, 0.03960084, 0.02268908, 0.66355042, 0.68340336],
       [0.23907563, 0.88361345, 0.79779412, 0.26733193, 0.26533613],
       [0.1210084 , 0.88907563, 0.8342437 , 0.05829832, 0.02972689],
       [0.50934874, 0.41092437, 1.        , 0.41838235, 0.66281513],
       [0.66922269, 0.38518908, 0.25273109, 0.87972689, 0.29212185],
       [0.71439076, 0.68655462, 0.23487395, 0.31113445, 0.56334034]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [116]:
#Code here
arr = np.array(eval(input()))
n = int(input())
np.partition(arr, -n)[-3]

(12,34,40,7,1,0)
3


np.int64(12)

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```italicized text
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [182]:
#code here
a = np.array([1, 2, 3])
np.hstack((np.repeat(a, 3), np.tile(a,3)))



array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])